posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post,PostDeleteView,PostUpdateView

app_name =  'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main_post_view'),
    path('liked/', like_unlike_post, name="like_post_view"),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post_update"),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invite_received,
    invite_profile_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    my_friends,
    get_users_posts,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all_profiles_view'), 
    path('timeline/', get_users_posts, name="users_posts"),
    path('friends/', my_friends, name='my_friends_view'),    
    path('myprofile/', my_profile_view, name='my_profile_view'),
    path('my_invites/', invite_received, name='my_invites_view'),
    path('to_invite/', invite_profile_list_view, name='invite_profiles_view'),
    path('send_invite/', send_invitation, name='send_invite'),
    path('remove_friend/', remove_from_friends, name='remove_friend'),    
    path('<slug>/', ProfileDetailView.as_view(), name='profiles_detail_view'),
    path('my_invites/accept/', accept_invitation, name='accept_invite'),
    path('my_invites/reject/', reject_invitation, name='reject_invite'),
    
]

social_media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
from .views import home
from accounts.views import login_view,register_view,logout_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/login/', login_view, name='login_view'),
    path('accounts/signup/', register_view, name='signup_view'),
    path('accounts/logout/', logout_view, name='logout_view'),
    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'email', 'country', 'avatar')
        

profiles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Profile,Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView,DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
# Create your views here.

@login_required
def get_users_posts(request, *args, **kwargs):
    profile = Profile.objects.get(user=request.user)
    users_posts = Post.objects.filter(author = profile)
    is_empty = False

    if len(users_posts) == 0:
        is_empty = True

    context = {
        'posts':users_posts,
        'is_empty':is_empty,
    }

    return render(request, 'profiles/timeline.html', context)

@login_required
def my_friends(request):
    profile = Profile.objects.get(user = request.user)
    friends = profile.get_friends()
    friends_profile = []
    for friend in friends:
        temp = Profile.objects.get(user = friend)
        friends_profile.append(temp)

    is_empty = False
    if len(friends_profile) == 0:
        is_empty =True

    context = {
        'friends':friends_profile,
        'is_empty':is_empty,
    }

    return render(request, 'profiles/friends_list.html', context)

@login_required
def my_profile_view(request):
    #getting the profile of the user who is logged in
    profile = Profile.objects.get(user = request.user)

    #Creating form from the model 
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    
    #this act as a flag which changes to true on a certain condition
    confirm = False

    if request.method == "POST":
        if form.is_valid():
            full_name = form.first_name + " " + form.last_name
            form.full_name = full_name
            form.save()
            confirm = True
    
    context = {
        'profile':profile,
        'form': form,
        'confirm':confirm,
    }

    return render(request, 'profiles/myprofile.html', context)

@login_required
def invite_received(request):
    #geting the profile of the logged_in user
    profile = Profile.objects.get(user = request.user)

    #using the extended behaviour of the objects
    qs = Relationship.objects.invitations_received(profile)

    results = list(map(lambda x: x.sender, qs))  #get sender from qs and insert it into result
    is_empty = False

    if len(results) == 0:
        is_empty = True

    context = {
        'qs':results,
        'is_empty':is_empty,
    }

    return render(request, 'profiles/my_invites.html', context)

@login_required
def accept_invitation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')       
        sender = Profile.objects.get(pk=pk)         #getting sender from primary key
        receiver = Profile.objects.get(user=request.user)    
        rel = get_object_or_404(Relationship,sender=sender,receiver=receiver) # another way of getting the object
        if rel.status == 'send':
            rel.status = "accepted"
            rel.save()
            sender.friends.add(receiver.user)
            receiver.friends.add(sender.user)
            sender.save()
            receiver.save()
    return redirect('profiles:my_invites_view')
         
@login_required
def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)         #getting sender from primary key
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship,sender=sender,receiver=receiver)
        rel.delete()
    return redirect('profiles:my_invites_view')

@login_required
def invite_profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)
    is_empty = False

    if len(qs) == 0:
        is_empty = True
    
    profile = Profile.objects.get(user = user)
    rel_1 = Relationship.objects.filter(receiver=profile) 
    rel_receiver = set()

    rel_2 = Relationship.objects.filter(sender=profile)
    rel_sender = set()

    for item in rel_1:
        rel_receiver.add(item.sender.user)   #adding sender to the set

    for item in rel_2:
        rel_sender.add(item.receiver.user)   #adding receiver to the set
    
    final_rel = rel_receiver.union(rel_sender)

    if len(qs) == len(final_rel):            #checking if length of both are equal then 
        is_empty = True                      #there is no user left to send the request

    context = {
        'qs':qs,
        'is_empty':is_empty,
        'rel_receiver':final_rel,
    }

    return render(request, 'profiles/invite_profile_list.html', context)

"""
def profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)
    context = {'qs':qs}
    return render(request, 'profiles/profile_list.html', context)
"""

#corresponding class based view to above function view
class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = "qs"                        #this refers to the context  

    #get_query_set is used to overrides the default query_set
    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    #this is used to add additional data to context data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context["profile"] = profile
        rel_r = Relationship.objects.filter(sender=profile)    #it store relationship we send to other user
        rel_s = Relationship.objects.filter(receiver=profile)  #it store relationship send by other user to our profile
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)

        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["is_empty"] = False

        if len(self.get_queryset()) == 0:
            context["is_empty"] = True
        
        return context

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail.html'
    
    #overriding the default get_object to get some extra functionality
    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile
    
    #overriding default get_context_data
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        context["profile"] = profile
        rel_r = Relationship.objects.filter(sender=profile)    #it store relationship we send to other user
        rel_s = Relationship.objects.filter(receiver=profile)  #it store relationship send by other user to our profile
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context["posts"] = self.get_object().get_authors_post()
        context["len_posts"] = True if len(self.get_object().get_authors_post()) > 0 else False
        return context




# function for changing the state from (add to friends)-> (waiting for approval)
@login_required
def send_invitation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')       #fetching profile_pk from form in profile_list.html 
        user = request.user                       
        sender = Profile.objects.get(user=user)   
        receiver = Profile.objects.get(pk=pk)     #getting receiver from pk of the profile object
        
        #creating a new relatioship b/w sender and receiver
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send') 

        return redirect(request.META.get('HTTP_REFERER'))  # redirect to the same page
    
    #when the request is not POST request
    return redirect('profiles:my_profile_view')  

# function for removing the friends from the friend list 
@login_required
def remove_from_friends(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')        
        user = request.user                       
        sender = Profile.objects.get(user=user)   
        receiver = Profile.objects.get(pk=pk)

        #complex lookup using Q 
        #since we dont know who send the request to whom so we need to search both ways
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender)))
        
        rel.delete()                                 
        return redirect(request.META.get('HTTP_REFERER'))  # redirect to the same page
    
    #when the request is not POST request
    return redirect('profiles:my_profile_view') 
        

profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
Profile Detail
{% endblock title %}


{% block content %}
    <h3 align="center">Profile: {{object.first_name}} {{object.last_name}}</h3>
    <div class="ui grid" style="margin-top:5px;">
        <div class="row">
            <div class="four wide column">
                <img class="ui small rounded image" src ={{object.avatar.url}} style="margin-left:50px;">
                <h1 style="margin-left:50px;">{{object.user}}</h1>
                <div class="ui vertical fluid menu">
                    
                    <div class="item">
                        Posts
                        <div class="ui label">
                            {{object.get_no_of_post}}
                        </div>
                    </div>

                    <div class="item">
                        Likes Given
                        <div class="ui label">
                            {{object.get_no_of_likes_given}}
                        </div>
                    </div>

                    <div class="item">
                        Likes Received
                        <div class="ui label">
                            {{object.get_no_of_likes_received}}
                        </div>
                    </div>

                    <div class="item">
                        Friends
                        <div class="ui label">
                            {{object.get_friends_no}}
                        </div>
                    </div>
                </div>
                    <!--form for displaying remove from friends button-->
                    {% if object.user not in rel_receiver and object.user not in rel_sender %}

                        <!--sending this form to send invitation function in the form of request-->
                        <form action="{% url 'profiles:send_invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{object.pk}}>
                            <!--if user is not in both receiver and sender list then there is no relationship btw them-->
                            <button type="submit" class="ui positive basic button" style="margin-left:30px;"><i class="plus square icon"></i>Add to friends</button>
                        </form>

                    {% endif %}

                    <br>
                    <!--if we has send invitation but other user has not accepted it-->
                    {% if object.user in rel_receiver and request.user not in object.friends.all %}
                        <button class="ui disabled button" style="width: 148px; margin-left:30px;">Request pending</butotn>
                    {% endif %}

                    <!--form for displaying add to friends button-->
                    {% if request.user in object.friends.all %}
                        <form action="{% url 'profiles:remove_friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{object.pk}}>
                            <button type="submit" class="ui negative basic button" style="margin-left:30px;"><i class="minus square icon"></i>Remove from friends</button>                            
                        </form>
                    {% endif %}
            </div>
            <div class="one wide column">
            </div>

            <div class="eleven wide column">
                <table class="ui very basic table" >
                    <tbody>
                        <tr>
                            <td>First name</td>
                            <td>{{object.first_name}}</td>
                        </tr>
                        <tr>
                            <td>Last name</td>
                            <td>{{object.last_name}}</td>
                        </tr>
                        <tr>
                            <td>Bio</td>
                            <td>{{object.bio}}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>{{object.email}}</td>
                        </tr>
                        <tr>
                            <td>Country</td>
                            <td>{{object.country}}</td>
                        </tr>
                        <tr>
                            <td>Friends</td>
                            <td>{{object.get_friends_no}}</td>
                        </tr>
                        <tr>
                            <td>Posts</td>
                            <td>{{object.get_no_of_post}}</td>
                        </tr>
                        <tr>
                            <td>Created on</td>
                            <td>{{object.created}}</td>
                        </tr>
                        <tr>
                            <td>Last updated on</td>
                            <td>{{object.updated}}</td>
                        </tr>
                        <tr>
                            <td>Likes(given/received)</td>
                            <td>{{object.get_no_of_likes_given}}/{{object.get_no_of_likes_received}}</td>
                        </tr>
                    </tbody>
                </table>



                {% if len_posts %}
                    <h3>Recent posts</h1>
                    {% for post in posts %}
                        <div class="ui segment fluid">
                            {{post.content}}
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>No posts of this user</h1>
                {% endif %}
            </div> 
        </div>
    </div>
{% endblock content %}

profiles/templates/profiles/friends_list.html
{% extends 'base.html' %}

{% block title %}
Friends
{% endblock title %}

{% block content %}
{% if is_empty %}
<h1>No friends here</h1>
{% endif %}


<div class="ui eight column grid">
    {% for friend in friends %}
    <div class="column" title="{{friend.bio}}">
        <div class="ui fluid card" style="box-shadow:none;">
            <div class="image" style="background-color:#f8f8f8 !important;">
                <img src="{{friend.avatar.url}}">
            </div>
            <div class="content" style="background-color:#f8f8f8 !important; border:none; font-size:12px;" align="center">
                <a href="{{friend.get_absolute_url}}" class="header">{{friend.first_name}} {{friend.last_name}}</a>
                <div class="meta">
                    <span class="date">Joined on - {{friend.created|date}}</span><br>
                    <i class="user icon"></i>{{friend.get_friends_no}} Friends
                </div>
            </div>
        </div>
    </div>
    {% comment %} <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="two wide column">
                    <img class="ui small circular image" src="{{friend.avatar.url}}">
                </div>

                <div class="eleven wide column">
                    <h3>{{friend.user}}</h3>
                    <p>{{friend.bio}}</p>
                </div>

                <div class="three wide column" style="margin-top:15px;">
                    <a href="{{friend.get_absolute_url}}">
                        <button class="ui primary button" style="margin-bottom:5px; width: 150px">
                            view profile
                        </button>
                    </a>

                    {% if request.user in friend.friends.all %}
                    <form action="{% url 'profiles:remove_friend' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{friend.pk}}>
                        <button type="submit" class="ui negative basic button"><i class="minus square icon"></i>Remove
                            friend</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    {% endfor %}
</div>
{% endblock content %}

profiles/templates/profiles/invite_profile_list.html
{% extends 'base.html' %}

{% block title %}
invites friends
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No user available</h1>
    {% endif %}
    <ul>
        {% for obj in qs %}
            {% if obj.user not in rel_receiver %}
                <div class="ui segment">
                    <div class="ui grid">
                        <div class="row">
                            <div class="two wide column">
                                <img class="ui small circular image" src={{obj.avatar.url}}>
                            </div>

                            <div class="eleven wide column">
                                <h3>{{obj.user}}</h3>
                                <p>{{obj.bio}}</p>
                            </div>

                            <div class="three wide column" style="margin-top:15px;">
                                <a href="{{obj.get_absolute_url}}">
                                    <button class="ui primary button" style="width:148px; margin-bottom:5px;">
                                        view profile
                                    </button>
                                </a>
                            
                                <form action="{% url 'profiles:send_invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="ui positive basic button" ><i class="plus square icon"></i>Send Request</button>
                                </form>            
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock content %}

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
my invites
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No invitation here. </h1>
    {% endif %}
    <ul>
        {% for obj in qs %}
            <div class="ui segment">
                <div class="ui grid">
                    <div class="row">
                        
                        <div class="two wide column">
                            <img class="ui small circular image" src = {{obj.avatar.url}}>
                        </div>

                        <div class="eleven wide column">
                            <h3>{{obj.user}}</h3>
                            <p>{{obj.bio}}</p>
                        </div>

                        <div class="three wide column">
                            <a href="{{obj.get_absolute_url}}">
                                <button class="ui primary button" style="width:160px; margin-bottom:5px;">
                                    view profile
                                </button>
                            </a>
                            
                            <form action="{% url 'profiles:accept_invite' %}" method = "POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button" style="width:160px; margin-bottom:5px;">
                                    <i class="check icon"></i>Accept request
                                </button>
                            </form>
                            
                            <form action="{% url 'profiles:reject_invite' %}" method = "POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui negative basic button" style="width:160px;">
                                    <i class="close icon"></i>Reject request
                                </button> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No profile to interact with</h1>
    {% endif %}
    {% for obj in qs %}             <!--qs is equivalent to object_list-->
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    
                    <div class="two wide column">
                        <img class="ui small circular image" src="{{obj.avatar.url}}">
                    </div>

                    <div class="eleven wide column">
                        
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                    </div>

                    <div class="three wide column" style="margin-top:15px;">
                        <a href="{{obj.get_absolute_url}}">
                            <button class="ui primary button" style="margin-bottom:5px; width: 150px">
                                view profile
                            </button>
                        </a>
                         
                        <!--form for displaying remove from friends button-->
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}

                            <!--sending this form to send invitation function in the form of request-->
                            <form action="{% url 'profiles:send_invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <!--if user is not in both receiver and sender list then there is no relationship btw them-->
                                <button type="submit" class="ui positive basic button" style="width:150px;"><i class="plus square icon"></i>Add to friends</button>
                            </form>

                        {% endif %}

                        <br>
                        <!--if we has send invitation but other user has not accepted it-->
                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button" style="width: 150px;">Request pending</butotn>
                        {% endif %}

                        <!--form for displaying add to friends button-->
                        {% if request.user in obj.friends.all %}
                            <form action="{% url 'profiles:remove_friend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui negative basic button"><i class="minus square icon"></i>Remove friend</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
    
{% endblock content %}

profiles/templates/profiles/timeline.html
{% extends 'base.html' %}

{% block title %}
Timeline
{% endblock title %}

{% block content %}
{% if is_empty %}
<div style="margin-top:230px;" align="center">
    <h3>No Post available</h3>
</div>
{% else %}
{% for post in posts %}
<div class="ui fluid card">
    <div class="content">
        <div class="right floated meta">
            <div class="ui grid">
                <div class="row">
                    <!--if logged in user matches the post user then only display update and delete button-->
                    {% ifequal request.user post.author.user %}
                    <a href="{% url 'posts:post_update' post.pk %}"><button class="ui button"
                            style="background-color: transparent !important;">Update</button></a>
                    <a href="{% url 'posts:post_delete' post.pk %}"><button class="ui button"
                            style="background-color: transparent !important;">Delete</button></a>
                    {% endifequal %}
                </div>
            </div>
        </div>
        <img class="ui avatar image" src={{post.author.avatar.url}}>
        {{ post.author.user }} - {{ post.created|timesince}} ago
    </div>
    <div class="ui fluid image">
        {% if post.image %}
        <img src={{post.image.url}}>
        {% endif %}
    </div>
    <div class="content">
        <p> {{ post.content }} </p>
        <div class="right floated">
            <form action="{% url 'posts:like_post_view' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="post_id" value={{post.id}}>
                {% if profile not in post.liked.all %}
                <i class="thumbs up icon"></i>
                <span> {{post.no_of_likes}}</span>
                {% else %}
                <i class="thumbs down icon"></i>
                <span> {{post.no_of_likes}}</span>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}