posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post,PostDeleteView,PostUpdateView

app_name =  'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main_post_view'),
    path('liked/', like_unlike_post, name="like_post_view"),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post_update"),
]

profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invite_received,
    invite_profile_list_view,
    ProfileListView,
    ProfileDetailView,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    my_friends,
    get_users_posts,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all_profiles_view'), 
    path('timeline/', get_users_posts, name="users_posts"),
    path('friends/', my_friends, name='my_friends_view'),    
    path('myprofile/', my_profile_view, name='my_profile_view'),
    path('my_invites/', invite_received, name='my_invites_view'),
    path('to_invite/', invite_profile_list_view, name='invite_profiles_view'),
    path('send_invite/', send_invitation, name='send_invite'),
    path('remove_friend/', remove_from_friends, name='remove_friend'),    
    path('<slug>/', ProfileDetailView.as_view(), name='profiles_detail_view'),
    path('my_invites/accept/', accept_invitation, name='accept_invite'),
    path('my_invites/reject/', reject_invitation, name='reject_invite'),
    
]

social_media/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
from .views import home
from accounts.views import login_view,register_view,logout_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/login/', login_view, name='login_view'),
    path('accounts/signup/', register_view, name='signup_view'),
    path('accounts/logout/', logout_view, name='logout_view'),
    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/main/home.html
{% load static %}
{% url 'login_view' as path_to_login %}
{% url 'signup_view' as path_to_signup %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css ADD HERE-->
    <link rel="stylesheet" type="text/css" href= {% static 'style.css' %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>Social Media</title>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Site Properties -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

    <style type="text/css">

    .hidden.menu {
      display: none;
    }
    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }
    body {
      background: url("{% static 'images/background_img.jpg' %}") no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    .box {
      width: 700px;
      height: 500px;
      margin-left: 0px;
      background: url("{% static 'images/people_img.svg' %}") no-repeat center center;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      position: fixed;
      right: 0px;
      bottom: 0px;
      
    }
  
  </style>  
</head>
<body>
  <div style="position: static;">
  <div class="box">
  </div>
  <div style="left: 30px; position:fixed">
    <div class="pusher">
      <div class="ui vertical masthead center aligned segment">
        <div class="ui text container">
          <h1 class="ui header">
            Social Media
          </h1>
          <h2>Post <strike>whatever</strike> you want when you want to.</h2>
          <br>
          <div style="margin-bottom:9px;">
          <a href="{{path_to_login}}" class="ui blue button" style="width:90px;">Log in</a>
          <a href="{{path_to_signup}}" class="ui green button"style="width:90px;">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div> 
</body>
</html>

templates/main/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIn</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style class="text/css">
        {% comment %} body {
            background: url("{% static 'images/light_background.jpg' %}") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        } {% endcomment %}
    </style>
</head>
<body>
    <div style="padding-top:30px;" align="center" class="mt-4">
        <h2 style="padding-bottom: 8px;">Welcome Aboard</h2>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <a class = "ml-2" style="text-align: center;" href="{% url 'password_reset' %}">Forgot Password ?</a>
            <br>
            <br>
            <button type="Submit" class="btn btn-dark">Login</button>
        </form>
    </div>
</body>
</html>

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main_post_view' as path_to_posts %}
{% url 'profiles:my_profile_view' as path_to_my_profile %}
{% url 'profiles:my_invites_view' as path_to_my_invites %}
{% url 'profiles:invite_profiles_view' as path_to_invites  %}
{% url 'profiles:all_profiles_view' as path_to_all_profiles %}
{% url 'profiles:my_friends_view' as path_to_friends %}
{% url 'profiles:users_posts' as path_to_timeline %}
{% url 'logout_view' as path_to_logout %}
{% url 'login_view' as path_to_login %}

<div class="ui secondary pointing menu nav"
    style="height:60px; position:sticky; top:0; z-index:1; background-color: white;">
    <div class="ui container">
        <h3 style="margin-left:-80px; padding-right:50px; padding-top: 8px;">Social Media &reg;</h3>
        <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
            Dashboard
        </a>
        {% if request.user.is_authenticated %}
        <a href="{{path_to_timeline}}" class="{% if request.path == path_to_timeline %}active{% endif %} item">
            Timeline
        </a>
        <a  href="{{path_to_friends}}" class="{% if request.path == path_to_friends %}active{% endif %} item">
            Friends
            <div class="mini floating circular ui red label" style="top:0px;">{{friend_count}}</div>
        </a>
        {% endif %}
        <div class="right menu">
            {% if request.user.is_authenticated %}
            <div class="item">
                <div class="ui dropdown"> Invites
                    <i class="ui dropdown icon"></i>
                    <div class="menu">
                        {% comment %} <a href="{{path_to_all_profiles}}"
                            class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                            All Profiles
                        </a> {% endcomment %}
                        <a href="{{path_to_invites}}"
                            class="{% if request.path == path_to_invites %}active{% endif %} item">
                            Sent
                        </a>
                        <a href="{{path_to_my_invites}}"
                            class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                            Received &nbsp;&nbsp;&nbsp;
                            <div class="ui small circular red horizontal label">
                                {{invites_no}}
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% comment %} <div class="item" style="padding-bottom:0px; padding-right:30px;">
                <form action="" method="GET">
                    <!--<div class="ui action left icon input">-->
                    <div class="ui icon input" style="">
                        <input id="search_here" class="prompt transparent" type="text" name='q' placeholder="search user...">
                        <i class="search icon"></i>
                        <!--<button type='submit' class="ui button">Search</button>-->
                    </div>
                </form>
            </div> {% endcomment %}
            <div class="ui search" style="padding-right:30px;">
                <div class="ui icon input">
                    <input id="search_here" class="prompt" type="text" placeholder="Search user...">
                    <i class="search icon"></i>
                </div>
                <div class="results"></div>
            </div>

            <a style="padding:5px; padding-right:20px" href="{{path_to_my_profile}}"
                class="{% if request.path == path_to_my_profile %}active{% endif %} item" style="margin-top:10px;">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                {{request.user}}
            </a>

            <a style="margin-right:-30px" href="{{path_to_logout}}" class="ui item">Logout</a>
            {% else %}
            <a href="{{path_to_login}}" class="ui item">
                Login
            </a>
            {% endif %}
        </div>
    </div>
</div>
<script>
    const data = '{{qs_json}}'
    const rdata = JSON.parse(data.replace(/&quot;/g, '"'))
    
    //input.addEventListener('keyup', (e)=>{
    //    filtered_arr = rdata.filter(Profile=> (Profile['first_name'].toLowerCase()+" "+Profile['last_name'].toLowerCase()).includes(e.target.value.toLowerCase()))
    //})


    var filtered_arr = [];

    rdata.forEach(function(item){
	var obj = {
		title : item.first_name + " "+ item.last_name
	};
	filtered_arr.push(obj);    
    });
    
    $('.ui.search')
        .search({
        source: filtered_arr
    });

</script>

templates/main/signup.html
<!DOCTYPE html>
<html lang="en" >
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    {% load crispy_forms_tags %}
    <style type="text/css">
        {% comment %} body {
            background: url("{% static 'images/light_background.jpg' %}") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        } {% endcomment %}
    </style>
</head>
<body>
    <div align="center" class="mt-4 mb-4"><h2>SignUp</h2></div>
    <div style="padding-left:300px; padding-right:300px;">
        <form method="POST" class="ui form">
            {% csrf_token %}
            {{form|crispy}}
            <button type="Submit" class="btn btn-dark">SignUp</button>
        </form>
    </div>
</body>
</html>